-- ============================================================
-- ServSaude - 03 - tabela e funcoes auxiliares de validacao
-- Origem: servsaude_schema_completo_fks_validacoes.sql
-- Execute conforme a numeracao do arquivo.
-- ============================================================

CREATE TABLE IF NOT EXISTS public._migration_validation_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_type text NOT NULL,
    table_name text NOT NULL,
    column_name text,
    referenced_table text,
    referenced_column text,
    issue_count bigint NOT NULL DEFAULT 0,
    details jsonb,
    created_at timestamptz DEFAULT now()
);

CREATE OR REPLACE FUNCTION public._table_exists(p_table text)
RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = p_table
    );
END;
$$;

CREATE OR REPLACE FUNCTION public._column_exists(p_table text, p_column text)
RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = p_table
          AND column_name = p_column
    );
END;
$$;

CREATE OR REPLACE FUNCTION public._constraint_exists(p_table text, p_constraint text)
RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = p_table
          AND constraint_name = p_constraint
    );
END;
$$;

CREATE OR REPLACE FUNCTION public._validate_fk_orphans(
    p_source_table text,
    p_source_column text,
    p_target_table text,
    p_target_column text
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_count bigint;
    v_sql text;
BEGIN
    IF NOT public._table_exists(p_source_table)
       OR NOT public._table_exists(p_target_table)
       OR NOT public._column_exists(p_source_table, p_source_column)
       OR NOT public._column_exists(p_target_table, p_target_column)
    THEN
        INSERT INTO public._migration_validation_issues (
            issue_type, table_name, column_name, referenced_table, referenced_column, issue_count, details
        )
        VALUES (
            'MISSING_TABLE_OR_COLUMN',
            p_source_table,
            p_source_column,
            p_target_table,
            p_target_column,
            1,
            jsonb_build_object(
                'source_table_exists', public._table_exists(p_source_table),
                'target_table_exists', public._table_exists(p_target_table),
                'source_column_exists', public._column_exists(p_source_table, p_source_column),
                'target_column_exists', public._column_exists(p_target_table, p_target_column)
            )
        );

        RETURN 1;
    END IF;

    v_sql := format(
        'SELECT count(*) FROM public.%I s
         WHERE s.%I IS NOT NULL
           AND NOT EXISTS (
               SELECT 1
               FROM public.%I t
               WHERE t.%I = s.%I
           )',
        p_source_table,
        p_source_column,
        p_target_table,
        p_target_column,
        p_source_column
    );

    EXECUTE v_sql INTO v_count;

    IF v_count > 0 THEN
        INSERT INTO public._migration_validation_issues (
            issue_type, table_name, column_name, referenced_table, referenced_column, issue_count, details
        )
        VALUES (
            'FK_ORPHAN_RECORDS',
            p_source_table,
            p_source_column,
            p_target_table,
            p_target_column,
            v_count,
            jsonb_build_object('message', 'Existem registros Ã³rfÃ£os antes da criaÃ§Ã£o da foreign key.')
        );
    END IF;

    RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public._add_fk_if_valid(
    p_source_table text,
    p_source_column text,
    p_target_table text,
    p_target_column text,
    p_constraint text
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_orphans bigint;
    v_sql text;
BEGIN
    v_orphans := public._validate_fk_orphans(
        p_source_table,
        p_source_column,
        p_target_table,
        p_target_column
    );

    IF v_orphans > 0 THEN
        RAISE NOTICE 'FK ignorada: %.% -> %.% possui % problema(s).',
            p_source_table, p_source_column, p_target_table, p_target_column, v_orphans;
        RETURN;
    END IF;

    IF public._constraint_exists(p_source_table, p_constraint) THEN
        RAISE NOTICE 'Constraint jÃ¡ existe: %', p_constraint;
        RETURN;
    END IF;

    v_sql := format(
        'ALTER TABLE public.%I
         ADD CONSTRAINT %I
         FOREIGN KEY (%I)
         REFERENCES public.%I(%I)
         ON UPDATE CASCADE
         ON DELETE RESTRICT
         NOT VALID',
        p_source_table,
        p_constraint,
        p_source_column,
        p_target_table,
        p_target_column
    );

    EXECUTE v_sql;

    RAISE NOTICE 'FK criada como NOT VALID: %', p_constraint;
END;
$$;

-- ============================================================
-- ValidaÃ§Ãµes e criaÃ§Ã£o segura de Foreign Keys
-- As FKs sÃ£o criadas como NOT VALID para evitar travar importaÃ§Ãµes grandes.
-- Depois de resolver pendÃªncias, execute os VALIDATE CONSTRAINTS no final.
-- ============================================================

