-- ============================================================
-- Schema corrigido — ServSaúde
-- Compatível com PostgreSQL / Supabase
-- Gerado a partir do SQL extraído do dump legado
-- ============================================================

CREATE SCHEMA IF NOT EXISTS public;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

-- ============================================================
-- Tabela: public.adesao_reducao_margem
-- ============================================================
CREATE TABLE IF NOT EXISTS public.adesao_reducao_margem (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adesao_id bigint NOT NULL,
    tipo_reducao integer NOT NULL,
    valor numeric(8,2) NOT NULL,
    data_inicio date NOT NULL,
    data_fim date NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.adesoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.adesoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operadora_id bigint NOT NULL,
    empresa_id bigint,
    secretaria_id bigint,
    conveniado_id bigint NOT NULL,
    grupo_familiar integer,
    produto_id bigint NOT NULL,
    produto_preco_id bigint,
    matricula character varying(255),
    tipo_cliente integer NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    data_inicio date NOT NULL,
    data_fim date,
    data_primeiro_pgto date,
    justificativa_encerramento character varying(255),
    dv character varying(255),
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    salario_atual numeric(13,2),
    motivo_encerramento_id integer
);

-- ============================================================
-- Tabela: public.bancos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.bancos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.boleto_lancamentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.boleto_lancamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boleto_id bigint NOT NULL,
    lancamento_id bigint NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.boletos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.boletos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operadora_id bigint NOT NULL,
    data_emissao date NOT NULL,
    data_vencimento date NOT NULL,
    valor_original numeric(8,2) NOT NULL,
    nosso_numero integer NOT NULL,
    numero_titulo_cliente character varying(255),
    agencia character varying(255),
    conta character varying(255),
    endereco character varying(255),
    cidade character varying(255),
    uf character varying(255),
    indicador_permissao_recebimento_parcial character varying(255) DEFAULT 'N'::character varying NOT NULL,
    indicador_pix character varying(255) DEFAULT 'S'::character varying NOT NULL,
    pagador_tipo_inscricao character varying(255) NOT NULL,
    pagador_numero_inscricao character varying(255) NOT NULL,
    pagador_nome character varying(255) NOT NULL,
    pagador_endereco character varying(255) NOT NULL,
    pagador_cep character varying(255) NOT NULL,
    pagador_cidade_id bigint NOT NULL,
    pagador_bairro character varying(255) NOT NULL,
    demonstrativo text,
    desconto_tipo integer DEFAULT 0 NOT NULL,
    desconto_data_expiracao date,
    desconto_porcentagem numeric(8,2),
    desconto_valor numeric(8,2),
    multa_tipo integer DEFAULT 0 NOT NULL,
    multa_data date,
    multa_porcentagem numeric(8,2),
    multa_valor numeric(8,2),
    juros_tipo integer DEFAULT 0 NOT NULL,
    juros_porcentagem numeric(8,2),
    juros_valor numeric(8,2),
    pix_qrcode character varying(255),
    instrucoes1 character varying(255),
    instrucoes2 character varying(255),
    instrucoes3 character varying(255),
    instrucoes4 character varying(255),
    status integer DEFAULT 1 NOT NULL,
    codigo_estado_titulo integer DEFAULT 1 NOT NULL,
    error_message text,
    data_baixa date,
    boleto text,
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.canais_atendimento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.canais_atendimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    telefone character varying(255),
    email character varying(255),
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.cargos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cargos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.cbhpm
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cbhpm (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cbhpm_edicao_id bigint NOT NULL,
    procedimento_id bigint NOT NULL,
    codigo_porte character varying(255) NOT NULL,
    fracao_porte numeric(8,2) DEFAULT '1'::numeric,
    qtde_uco numeric(13,3) NOT NULL,
    qtde_filme numeric(13,3) NOT NULL,
    porte_anestesico_id bigint,
    nro_auxiliares integer,
    incidencia integer,
    ur boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.cbhpm_edicoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cbhpm_edicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano_edicao integer NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.cid
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cid (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    sexo_aplicavel character varying(255) NOT NULL,
    grave boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.cidades
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.comunicado_edicoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.comunicado_edicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano_edicao integer NOT NULL,
    uco numeric(8,2) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.comunicado_portes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.comunicado_portes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comunicado_edicao_id bigint NOT NULL,
    codigo_porte character varying(255) NOT NULL,
    valor numeric(8,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.contrato_profissionais
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contrato_profissionais (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_id bigint NOT NULL,
    prestador_id bigint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.conveniado_salarios
-- ============================================================
CREATE TABLE IF NOT EXISTS public.conveniado_salarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conveniado_id bigint NOT NULL,
    salario numeric(8,2) NOT NULL,
    data_competencia date NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.conveniados
-- ============================================================
CREATE TABLE IF NOT EXISTS public.conveniados (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orgao_expedidor_uf_id bigint,
    naturalidade_cidade_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    cpf character varying(255) NOT NULL,
    data_nascimento date NOT NULL,
    sexo smallint NOT NULL,
    rg character varying(255),
    orgao_expedidor character varying(255),
    cns character varying(255),
    nome_pai character varying(255),
    nome_mae character varying(255) NOT NULL,
    fone1 character varying(255),
    fone2 character varying(255),
    email character varying(255),
    foto text,
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    estado_civil integer DEFAULT 1 NOT NULL,
    pcd integer DEFAULT 2 NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    cargo_id integer
);

-- ============================================================
-- Tabela: public.dados_bancarios
-- ============================================================
CREATE TABLE IF NOT EXISTS public.dados_bancarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origem_id bigint NOT NULL,
    tabela character varying(255) NOT NULL,
    banco_id bigint NOT NULL,
    tipo smallint NOT NULL,
    agencia character varying(255),
    agencia_dv character varying(255),
    conta character varying(255),
    conta_dv character varying(255),
    operacao character varying(255),
    pix character varying(255),
    pix_tipo character varying(255),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.deflatores
-- ============================================================
CREATE TABLE IF NOT EXISTS public.deflatores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestadores_contratos_id bigint NOT NULL,
    procedimento_grupo_id bigint NOT NULL,
    tipo smallint NOT NULL,
    percentual numeric(8,2) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.documentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.documentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo integer NOT NULL,
    tabela text,
    origem_id integer,
    documento text,
    descricao text,
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.documentos_credenciamento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.documentos_credenciamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    complemento_descricao character varying(255),
    obrigatorio boolean DEFAULT true NOT NULL,
    active boolean DEFAULT true NOT NULL,
    tipo_pessoa integer DEFAULT 1 NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.editais_credenciamento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.editais_credenciamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    data_inicio date NOT NULL,
    data_fim date NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.edital_credenciamento_documentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.edital_credenciamento_documentos (
    edital_id bigint NOT NULL,
    documento_credenciamento_id bigint NOT NULL,
    obrigatorio boolean DEFAULT false NOT NULL,
    updated_at timestamptz DEFAULT '2024-04-22 07:40:35'::timestamp without time zone NOT NULL,
    PRIMARY KEY (edital_id, documento_credenciamento_id)
);

-- ============================================================
-- Tabela: public.empresa_produto
-- ============================================================
CREATE TABLE IF NOT EXISTS public.empresa_produto (
    empresa_id bigint NOT NULL,
    produto_id bigint NOT NULL,
    PRIMARY KEY (empresa_id, produto_id)
);

-- ============================================================
-- Tabela: public.empresa_user
-- ============================================================
CREATE TABLE IF NOT EXISTS public.empresa_user (
    user_id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    PRIMARY KEY (user_id, empresa_id)
);

-- ============================================================
-- Tabela: public.empresas
-- ============================================================
CREATE TABLE IF NOT EXISTS public.empresas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo smallint NOT NULL,
    cpf_cnpj character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    razao_social character varying(255) NOT NULL,
    abreviado text,
    fone character varying(255),
    email character varying(255),
    inscricao_municipal character varying(255),
    inscricao_estadual character varying(255),
    contato character varying(255),
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.empresas_verbas
-- ============================================================
CREATE TABLE IF NOT EXISTS public.empresas_verbas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    grupo_verba_id bigint
);

-- ============================================================
-- Tabela: public.enderecos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.enderecos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade_id bigint NOT NULL,
    tabela text,
    origem_id integer,
    tipo integer NOT NULL,
    cep text NOT NULL,
    endereco text NOT NULL,
    numero text,
    complemento text,
    bairro text,
    "default" boolean DEFAULT false NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.especialidades
-- ============================================================
CREATE TABLE IF NOT EXISTS public.especialidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    cbo character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.estados
-- ============================================================
CREATE TABLE IF NOT EXISTS public.estados (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    uf character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.failed_jobs
-- ============================================================
CREATE TABLE IF NOT EXISTS public.failed_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid character varying(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================
-- Tabela: public.fiscal_contrato_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fiscal_contrato_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_contrato_id bigint NOT NULL,
    contrato_id bigint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.fiscal_contratos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fiscal_contratos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    data_inicio date DEFAULT CURRENT_DATE NOT NULL,
    data_fim date NOT NULL,
    portaria character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.gestantes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.gestantes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conveniado_id bigint NOT NULL,
    data_inicio_gestacao date DEFAULT CURRENT_DATE NOT NULL,
    data_final_gestacao date,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.grau_parentesco
-- ============================================================
CREATE TABLE IF NOT EXISTS public.grau_parentesco (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.grupo_verbas
-- ============================================================
CREATE TABLE IF NOT EXISTS public.grupo_verbas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guia_importacoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guia_importacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequencial_transacao integer NOT NULL,
    lote integer NOT NULL,
    data_hora_arquivo timestamptz NOT NULL,
    prestador_id bigint,
    usuario_id bigint,
    versao_layout character varying(255) NOT NULL,
    arquivo character varying(255) NOT NULL,
    disco character varying(255) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guia_motivo_encerramento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guia_motivo_encerramento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(255) NOT NULL,
    termo character varying(255) NOT NULL,
    data_inicio_vigencia date,
    data_fim_vigencia date,
    data_fim_implantacao date,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guias
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamptz DEFAULT '2024-03-06 09:46:05'::timestamp without time zone NOT NULL,
    usuario_emissor_id bigint,
    prestador_id bigint,
    profissional_id bigint,
    conveniado_id bigint,
    solicitante_prestador_id bigint,
    lote_pagamento_id bigint,
    tipo_lancamento smallint DEFAULT '1'::smallint NOT NULL,
    tipo_autorizacao smallint DEFAULT '1'::smallint NOT NULL,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    carater_atendimento smallint DEFAULT '1'::smallint NOT NULL,
    guia_origem_id bigint,
    indicacao_clinica character varying(255),
    observacoes character varying(255),
    observacoes_internas character varying(255),
    urgente boolean DEFAULT false NOT NULL,
    conferido boolean DEFAULT false NOT NULL,
    status smallint DEFAULT '1'::smallint NOT NULL,
    data_hora_cancalamento timestamptz,
    cancelado_por_user_id bigint,
    motivo_cancelamento character varying(255),
    justifica_para_auditoria character varying(255),
    guia_importacao_id bigint,
    lote_importacao integer,
    numero_guia_prestador integer,
    data_autorizacao date,
    senha integer,
    data_validade_senha date,
    atendimento_rn character varying(255),
    cnes integer,
    tipo_faturamento integer,
    data_inicio_faturamento date,
    data_final_faturamento date,
    tipo_internacao integer,
    regime_internacao integer,
    diagnostico character varying(255),
    indicador_acidente integer,
    motivo_encerramento integer,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    tipo_autenticacao smallint,
    codigo_autenticacao character varying(255),
    autenticada boolean DEFAULT false NOT NULL
);

-- ============================================================
-- Tabela: public.guias_anexos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias_anexos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guia_id bigint,
    nome character varying(255),
    arquivo character varying(255),
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guias_atendimentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias_atendimentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamptz DEFAULT '2024-03-06 09:46:05'::timestamp without time zone NOT NULL,
    guia_itens_id bigint,
    quantidade numeric(8,2),
    usuario_id bigint,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.guias_auditoria
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias_auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_analise timestamptz DEFAULT '2024-03-06 09:46:05'::timestamp without time zone NOT NULL,
    guia_itens_id bigint NOT NULL,
    quantidade_autorizada numeric(8,2) NOT NULL,
    justificativa character varying(255),
    analise_usuario_id bigint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guias_historico
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias_historico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamptz DEFAULT '2024-03-06 09:46:05'::timestamp without time zone NOT NULL,
    guia_id bigint NOT NULL,
    guia_item_id bigint,
    historico character varying(255) NOT NULL,
    usuario_id bigint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.guias_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.guias_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_emissao timestamptz DEFAULT '2024-03-06 09:46:05'::timestamp without time zone NOT NULL,
    data_hora_autorizacao timestamptz,
    data_hora_atendimento timestamptz,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    guia_id bigint,
    referencia_tabela character varying(255) NOT NULL,
    referencia_id integer,
    quantidade_solicitada numeric(8,2),
    quantidade_atendida numeric(8,2),
    quantidade_glosa numeric(8,2),
    valor_unitario numeric(8,2),
    valor_unitario_glosa numeric(8,2),
    percentual_cooparticipacao numeric(8,2),
    valor_unitario_coparticipacao numeric(8,2),
    valor_total_coparticipacao numeric(8,2),
    percentual_item numeric(8,2),
    quantidade_faturada numeric(8,2),
    valor_unitario_faturado numeric(8,2),
    valor_total_faturado numeric(8,2),
    status smallint DEFAULT '1'::smallint NOT NULL,
    data_execucao date,
    hora_inicial time(0) without time zone,
    hora_final time(0) without time zone,
    codigo_tabela integer,
    codigo_despesa integer,
    codigo_procedimento character varying(255),
    quantidade_autorizada numeric(8,2),
    reducao_acrescimo numeric(8,2),
    valor_total numeric(8,2),
    grau_part integer,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.historico_credenciamentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.historico_credenciamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_credencimento_id bigint NOT NULL,
    user_id bigint NOT NULL,
    motivo character varying(255) NOT NULL,
    status integer NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.laboratorios
-- ============================================================
CREATE TABLE IF NOT EXISTS public.laboratorios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.lancamentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.lancamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    boleto_id integer,
    operadora_id bigint NOT NULL,
    prestador_id bigint,
    conveniado_id bigint,
    tipo_lancamento smallint DEFAULT '2'::smallint NOT NULL,
    data_hora timestamptz DEFAULT '2024-01-19 13:56:01'::timestamp without time zone NOT NULL,
    data_vencimento timestamptz NOT NULL,
    data_baixa timestamptz,
    tipo_pagamento smallint DEFAULT '1'::smallint NOT NULL,
    competencia_folha character varying(255),
    descricao character varying(255),
    valor numeric(8,2) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    grupo_verba_id bigint
);

-- ============================================================
-- Tabela: public.lancamentos_guias
-- ============================================================
CREATE TABLE IF NOT EXISTS public.lancamentos_guias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lancamento_id bigint NOT NULL,
    guia_id bigint NOT NULL,
    valor numeric(8,2) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.log_acessos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.log_acessos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamptz,
    usuario_id integer,
    usuario_nome text,
    ip text,
    navegador text,
    recurso text,
    registro_id integer,
    url character varying(255),
    action smallint,
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.log_operacoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.log_operacoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamptz,
    usuario_id integer,
    usuario_nome text,
    ip text,
    navegador text,
    recurso text,
    registro_id integer,
    log text,
    action smallint,
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.lote_pagamentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.lote_pagamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    lancamento_id bigint,
    data_hora timestamptz NOT NULL,
    referencia_pagamento date NOT NULL,
    status smallint DEFAULT '1'::smallint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.materiais
-- ============================================================
CREATE TABLE IF NOT EXISTS public.materiais (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo integer NOT NULL,
    codigo character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.materiais_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.materiais_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_edicao_id bigint NOT NULL,
    material_id bigint NOT NULL,
    valor numeric(8,2) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.material_edicoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.material_edicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edicao character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.medicamento_brasindice
-- ============================================================
CREATE TABLE IF NOT EXISTS public.medicamento_brasindice (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicamento_edicao_id bigint NOT NULL,
    medicamento_id bigint NOT NULL,
    pmc numeric(15,2) DEFAULT '0'::numeric NOT NULL,
    pfab numeric(15,2) DEFAULT '0'::numeric NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    fracao_pfab numeric(15,2) DEFAULT '0'::numeric NOT NULL,
    fracao_pmc numeric(15,2) DEFAULT '0'::numeric NOT NULL
);

-- ============================================================
-- Tabela: public.medicamento_edicoes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.medicamento_edicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edicao character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.medicamentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.medicamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratorio_id bigint NOT NULL,
    medicamento_edicao_id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    bras character varying(255) NOT NULL,
    in_ character varying(255) NOT NULL,
    dice character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    apresentacao character varying(255) NOT NULL,
    qtde_embalagem integer NOT NULL,
    ultima_versao integer NOT NULL,
    ean character varying(255) NOT NULL,
    ggrem character varying(255) NOT NULL,
    anvisa character varying(255) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.mensagens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.mensagens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id bigint,
    tipo integer NOT NULL,
    titulo character varying(255) NOT NULL,
    corpo text NOT NULL,
    idade_inicial integer,
    idade_final integer,
    data_inicial_exibicao date,
    data_final_exibicao date,
    visivel boolean DEFAULT true NOT NULL,
    fixado boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.mensalidades
-- ============================================================
CREATE TABLE IF NOT EXISTS public.mensalidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conveniado_id bigint NOT NULL,
    competencia date NOT NULL,
    produto_preco_id bigint NOT NULL,
    grupo_verba_id bigint,
    salario numeric(8,2) NOT NULL,
    percentual numeric(8,2) NOT NULL,
    valor numeric(8,2) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.menus
-- ============================================================
CREATE TABLE IF NOT EXISTS public.menus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    is_divisor boolean DEFAULT false NOT NULL,
    parameter character varying(255),
    link character varying(255),
    permission character varying(255),
    fixed_id integer,
    parent_id integer,
    icon_family character varying(255),
    icon character varying(255),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.migrations
-- ============================================================
CREATE TABLE IF NOT EXISTS public.migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);

-- ============================================================
-- Tabela: public.motivo_encerramentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.motivo_encerramentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motivo character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    tipo smallint DEFAULT '1'::smallint NOT NULL
);

-- ============================================================
-- Tabela: public.operadora_user
-- ============================================================
CREATE TABLE IF NOT EXISTS public.operadora_user (
    operadora_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (operadora_id, user_id)
);

-- ============================================================
-- Tabela: public.operadoras
-- ============================================================
CREATE TABLE IF NOT EXISTS public.operadoras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    razao_social character varying(255) NOT NULL,
    tipo smallint NOT NULL,
    cpf_cnpj character varying(255) NOT NULL,
    inscricao_municipal character varying(255),
    inscricao_estadual character varying(255),
    fone character varying(255),
    email character varying(255),
    certificado character varying(255),
    senha_certificado character varying(255),
    codigo_ans character varying(6),
    tipo_declarante integer NOT NULL,
    cpf_responsavel character varying(255) NOT NULL,
    indicador_situacao_declaracao character varying(255) NOT NULL,
    cnes character varying(7),
    ativo boolean DEFAULT true NOT NULL,
    percentual_max_desconto_coparticipacao numeric(8,2) DEFAULT 24.9 NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    boleto_nr_convenio integer,
    boleto_nr_carteira integer,
    boleto_nr_variacao_carteira integer,
    boleto_nr_controle integer,
    boleto_client_id character varying(255),
    boleto_client_secret text,
    boleto_gw_dev_app_key character varying(255),
    boleto_recebimento_parcial character varying(255) DEFAULT 'N'::character varying NOT NULL,
    boleto_indicador_pix character varying(255) DEFAULT 'S'::character varying NOT NULL,
    boleto_multa_tipo integer DEFAULT 0 NOT NULL,
    boleto_multa_dias_apos_vencimento integer DEFAULT 1,
    boleto_multa_porcentagem numeric(8,2),
    boleto_multa_valor numeric(8,2),
    boleto_juros_tipo integer DEFAULT 0 NOT NULL,
    boleto_juros_porcentagem numeric(8,2),
    boleto_juros_valor numeric(8,2),
    boleto_ambiente integer DEFAULT 1,
    boleto_cancelar_dias_apos_vencimento integer,
    boleto_forma_pagamento_apos_cancelar integer
);

-- ============================================================
-- Tabela: public.parametros
-- ============================================================
CREATE TABLE IF NOT EXISTS public.parametros (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter character varying(255) NOT NULL,
    field_label character varying(255) NOT NULL,
    component text,
    value character varying(255),
    possible_values character varying(255),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.permission_role
-- ============================================================
CREATE TABLE IF NOT EXISTS public.permission_role (
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (permission_id, role_id)
);

-- ============================================================
-- Tabela: public.permissions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    description character varying(255)
);

-- ============================================================
-- Tabela: public.personal_access_tokens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.personal_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    token character varying(64) NOT NULL,
    abilities text,
    last_used_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.porte_anestesicos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.porte_anestesicos (
    porte_anestesico character varying(255) DEFAULT '0'::character varying NOT NULL,
    porte character varying(255),
    PRIMARY KEY (porte_anestesico)
);

-- ============================================================
-- Tabela: public.prestador_contrato_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestador_contrato_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestadores_contratos_id bigint NOT NULL,
    edicao_medicamento_id bigint NOT NULL,
    acrescimo_medicamentos numeric(8,2),
    tabela_precos_id bigint,
    data_inicio date NOT NULL,
    data_fim date NOT NULL,
    tipo smallint NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    orcamento_previsto numeric(8,2),
    motivo_encerramento_id bigint,
    data_encerramento timestamptz
);

-- ============================================================
-- Tabela: public.prestador_contratos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestador_contratos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestador_id bigint NOT NULL,
    data date NOT NULL,
    codigo character varying(255) NOT NULL,
    ocorrencia character varying(255),
    objeto character varying(255) NOT NULL,
    observacoes character varying(255),
    reclamacoes character varying(255),
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.prestador_especialidades
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestador_especialidades (
    prestador_id bigint NOT NULL,
    especialidade_id bigint NOT NULL,
    PRIMARY KEY (prestador_id, especialidade_id)
);

-- ============================================================
-- Tabela: public.prestador_tipos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestador_tipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.prestador_user
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestador_user (
    prestador_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (prestador_id, user_id)
);

-- ============================================================
-- Tabela: public.prestadores
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestadores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint,
    prestadores_classificacao_estabelecimento_id bigint NOT NULL,
    orgao_expedidor_uf_id bigint,
    naturalidade_cidade_id bigint,
    tipo smallint NOT NULL,
    nome character varying(255) NOT NULL,
    razao_social character varying(255) NOT NULL,
    abreviado text,
    cpf_cnpj character varying(255) NOT NULL,
    data_nascimento date,
    rg character varying(255),
    orgao_expedidor character varying(255),
    nome_mae character varying(255),
    inscricao_municipal character varying(255),
    inscricao_estadual character varying(255),
    fone character varying(255),
    email character varying(255),
    financeiro_contato_nome character varying(255),
    financeiro_contato_fone character varying(255),
    financeiro_contato_email character varying(255),
    faturamento_contato_nome character varying(255),
    faturamento_contato_fone character varying(255),
    faturamento_contato_email character varying(255),
    tipo_conselho_classe smallint,
    numero_conselho_classe character varying(255),
    procedimentos boolean DEFAULT false NOT NULL,
    material boolean DEFAULT false NOT NULL,
    taxa boolean DEFAULT false NOT NULL,
    medicamentos boolean DEFAULT false NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    prestador_tipo_id integer
);

-- ============================================================
-- Tabela: public.prestadores_classificacao_estabelecimento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.prestadores_classificacao_estabelecimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    codigo character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.procedimento_subgrupos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.procedimento_subgrupos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    perc_reducao_segundo_procedimento numeric(8,2) NOT NULL,
    perc_reducao_terceiro_procedimento_em_diante numeric(8,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.procedimentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.procedimentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL,
    procedimento_subgrupo_id integer,
    descricao text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.procedimentos_grupos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.procedimentos_grupos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.produtos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.produtos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operadora_id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    abrangencia smallint NOT NULL,
    tipo_contratacao integer NOT NULL,
    tipo_carencia smallint NOT NULL,
    tipo_acomodacao integer NOT NULL,
    data_inicio date NOT NULL,
    data_fim date,
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.produtos_precos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.produtos_precos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id bigint NOT NULL,
    tipo_vinculo_id bigint,
    idade_inicial integer NOT NULL,
    idade_final integer NOT NULL,
    tipo_cobranca integer NOT NULL,
    tipo_cliente integer NOT NULL,
    descricao character varying(255) NOT NULL,
    valor numeric(8,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    grupo_verba_id bigint
);

-- ============================================================
-- Tabela: public.regra_cooparticipacao
-- ============================================================
CREATE TABLE IF NOT EXISTS public.regra_cooparticipacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id bigint NOT NULL,
    nome text NOT NULL,
    tempo_carencia integer,
    carencia boolean NOT NULL,
    sem_limite_para_gestante boolean DEFAULT false NOT NULL,
    auditoria boolean NOT NULL,
    ativo boolean NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.regra_cooparticipacao_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.regra_cooparticipacao_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regra_cooparticipacao_id bigint NOT NULL,
    qtde_inicial integer NOT NULL,
    qtde_final integer NOT NULL,
    percentual_cooparticipacao numeric(8,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.regra_cooparticipacao_procedimentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.regra_cooparticipacao_procedimentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    regra_cooparticipacao_id bigint NOT NULL,
    grupo_procedimento_id integer NOT NULL,
    subgrupo_procedimento_id integer,
    procedimento_id integer,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Tabela: public.remessa_desconto
-- ============================================================
CREATE TABLE IF NOT EXISTS public.remessa_desconto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    competencia date NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.remessa_desconto_item
-- ============================================================
CREATE TABLE IF NOT EXISTS public.remessa_desconto_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remessa_desconto_id bigint NOT NULL,
    adesao_id bigint NOT NULL,
    matricula character varying(255) NOT NULL,
    salario numeric(8,2) NOT NULL,
    desconto_maximo numeric(8,2) NOT NULL,
    valor_divida numeric(8,2) NOT NULL,
    coparticipacao numeric(8,2) NOT NULL,
    codigo_evento character varying(255) NOT NULL,
    valor numeric(8,2) NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.role_user
-- ============================================================
CREATE TABLE IF NOT EXISTS public.role_user (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- ============================================================
-- Tabela: public.roles
-- ============================================================
CREATE TABLE IF NOT EXISTS public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.secretarias
-- ============================================================
CREATE TABLE IF NOT EXISTS public.secretarias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    razao_social character varying(255) NOT NULL,
    cpf_cnpj character varying(255),
    inscricao_municipal character varying(255),
    inscricao_estadual character varying(255),
    fone character varying(255),
    email character varying(255),
    contato character varying(255),
    ativo boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz,
    abreviado character varying(255)
);

-- ============================================================
-- Tabela: public.solicitacoes_atualizacao_cadastral
-- ============================================================
CREATE TABLE IF NOT EXISTS public.solicitacoes_atualizacao_cadastral (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_solicitacao date DEFAULT CURRENT_DATE NOT NULL,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    prestador_id bigint,
    conveniado_id bigint,
    cidade_id bigint NOT NULL,
    endereco character varying(255),
    endereco_nro character varying(255),
    complemento character varying(255),
    bairro character varying(255),
    cep character varying(255),
    email character varying(255),
    telefone character varying(255),
    celular character varying(255),
    observacoes character varying(255),
    comprovante_endereco character varying(255),
    foto character varying(255),
    disk character varying(255),
    status smallint DEFAULT '1'::smallint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.solicitacoes_credenciamento
-- ============================================================
CREATE TABLE IF NOT EXISTS public.solicitacoes_credenciamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edital_credenciamento_id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    tipo integer DEFAULT 1 NOT NULL,
    cpf_cnpj character varying(255) NOT NULL,
    responsavel character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.solicitacoes_credenciamento_documentos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.solicitacoes_credenciamento_documentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacoes_credenciamento_id bigint NOT NULL,
    documento_credenciamento_id bigint NOT NULL,
    arquivo text,
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    nome_arquivo character varying(255)
);

-- ============================================================
-- Tabela: public.tabela_precos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tabela_precos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    comunicado_edicao_id bigint NOT NULL,
    cbhpm_edicao_id bigint NOT NULL,
    material_edicao_id bigint NOT NULL,
    valor_uco numeric(8,2) NOT NULL,
    valor_filme numeric(8,2) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.tabela_precos_itens
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tabela_precos_itens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_preco_id bigint NOT NULL,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    referencia_id integer NOT NULL,
    valor_porte numeric(8,2) NOT NULL,
    fracao_porte numeric(8,2) NOT NULL,
    qtde_uco numeric(8,2) NOT NULL,
    valor_uco numeric(8,2) NOT NULL,
    qtde_filme numeric(8,2) NOT NULL,
    valor_filme numeric(8,2) NOT NULL,
    valor_total numeric(8,2) NOT NULL,
    valor_customizado numeric(8,2),
    valor_final numeric(8,2) NOT NULL,
    preco_customizado boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.taxas
-- ============================================================
CREATE TABLE IF NOT EXISTS public.taxas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(255) NOT NULL,
    descricao character varying(255),
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.tipo_vinculos
-- ============================================================
CREATE TABLE IF NOT EXISTS public.tipo_vinculos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo smallint DEFAULT '1'::smallint NOT NULL,
    descricao text NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- Tabela: public.users
-- ============================================================
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    email text,
    password character varying(255) NOT NULL,
    fone character varying(255),
    cpf character varying(255),
    forget_token text,
    foto text,
    disk character varying(255) DEFAULT 'public'::character varying NOT NULL,
    active boolean DEFAULT true NOT NULL,
    colaborador boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- ============================================================
-- Índices auxiliares recomendados
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_adesao_reducao_margem_adesao_id ON public.adesao_reducao_margem (adesao_id);
CREATE INDEX IF NOT EXISTS idx_adesao_reducao_margem_deleted_at ON public.adesao_reducao_margem (deleted_at);
CREATE INDEX IF NOT EXISTS idx_adesao_reducao_margem_created_at ON public.adesao_reducao_margem (created_at);
CREATE INDEX IF NOT EXISTS idx_adesoes_operadora_id ON public.adesoes (operadora_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_empresa_id ON public.adesoes (empresa_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_secretaria_id ON public.adesoes (secretaria_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_conveniado_id ON public.adesoes (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_produto_id ON public.adesoes (produto_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_produto_preco_id ON public.adesoes (produto_preco_id);
CREATE INDEX IF NOT EXISTS idx_adesoes_status ON public.adesoes (status);
CREATE INDEX IF NOT EXISTS idx_adesoes_deleted_at ON public.adesoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_adesoes_created_at ON public.adesoes (created_at);
CREATE INDEX IF NOT EXISTS idx_adesoes_motivo_encerramento_id ON public.adesoes (motivo_encerramento_id);
CREATE INDEX IF NOT EXISTS idx_bancos_ativo ON public.bancos (ativo);
CREATE INDEX IF NOT EXISTS idx_bancos_created_at ON public.bancos (created_at);
CREATE INDEX IF NOT EXISTS idx_bancos_deleted_at ON public.bancos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_boleto_lancamentos_boleto_id ON public.boleto_lancamentos (boleto_id);
CREATE INDEX IF NOT EXISTS idx_boleto_lancamentos_lancamento_id ON public.boleto_lancamentos (lancamento_id);
CREATE INDEX IF NOT EXISTS idx_boleto_lancamentos_created_at ON public.boleto_lancamentos (created_at);
CREATE INDEX IF NOT EXISTS idx_boletos_operadora_id ON public.boletos (operadora_id);
CREATE INDEX IF NOT EXISTS idx_boletos_pagador_cidade_id ON public.boletos (pagador_cidade_id);
CREATE INDEX IF NOT EXISTS idx_boletos_status ON public.boletos (status);
CREATE INDEX IF NOT EXISTS idx_boletos_deleted_at ON public.boletos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_boletos_created_at ON public.boletos (created_at);
CREATE INDEX IF NOT EXISTS idx_canais_atendimento_email ON public.canais_atendimento (email);
CREATE INDEX IF NOT EXISTS idx_canais_atendimento_deleted_at ON public.canais_atendimento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_canais_atendimento_created_at ON public.canais_atendimento (created_at);
CREATE INDEX IF NOT EXISTS idx_cargos_ativo ON public.cargos (ativo);
CREATE INDEX IF NOT EXISTS idx_cargos_deleted_at ON public.cargos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cargos_created_at ON public.cargos (created_at);
CREATE INDEX IF NOT EXISTS idx_cbhpm_cbhpm_edicao_id ON public.cbhpm (cbhpm_edicao_id);
CREATE INDEX IF NOT EXISTS idx_cbhpm_procedimento_id ON public.cbhpm (procedimento_id);
CREATE INDEX IF NOT EXISTS idx_cbhpm_porte_anestesico_id ON public.cbhpm (porte_anestesico_id);
CREATE INDEX IF NOT EXISTS idx_cbhpm_deleted_at ON public.cbhpm (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cbhpm_created_at ON public.cbhpm (created_at);
CREATE INDEX IF NOT EXISTS idx_cbhpm_edicoes_ativo ON public.cbhpm_edicoes (ativo);
CREATE INDEX IF NOT EXISTS idx_cbhpm_edicoes_created_at ON public.cbhpm_edicoes (created_at);
CREATE INDEX IF NOT EXISTS idx_cbhpm_edicoes_deleted_at ON public.cbhpm_edicoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cid_created_at ON public.cid (created_at);
CREATE INDEX IF NOT EXISTS idx_cidades_estado_id ON public.cidades (estado_id);
CREATE INDEX IF NOT EXISTS idx_cidades_created_at ON public.cidades (created_at);
CREATE INDEX IF NOT EXISTS idx_cidades_deleted_at ON public.cidades (deleted_at);
CREATE INDEX IF NOT EXISTS idx_comunicado_edicoes_ativo ON public.comunicado_edicoes (ativo);
CREATE INDEX IF NOT EXISTS idx_comunicado_edicoes_created_at ON public.comunicado_edicoes (created_at);
CREATE INDEX IF NOT EXISTS idx_comunicado_edicoes_deleted_at ON public.comunicado_edicoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_comunicado_portes_comunicado_edicao_id ON public.comunicado_portes (comunicado_edicao_id);
CREATE INDEX IF NOT EXISTS idx_comunicado_portes_created_at ON public.comunicado_portes (created_at);
CREATE INDEX IF NOT EXISTS idx_comunicado_portes_deleted_at ON public.comunicado_portes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_contrato_profissionais_contrato_id ON public.contrato_profissionais (contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_profissionais_prestador_id ON public.contrato_profissionais (prestador_id);
CREATE INDEX IF NOT EXISTS idx_contrato_profissionais_deleted_at ON public.contrato_profissionais (deleted_at);
CREATE INDEX IF NOT EXISTS idx_contrato_profissionais_created_at ON public.contrato_profissionais (created_at);
CREATE INDEX IF NOT EXISTS idx_conveniado_salarios_conveniado_id ON public.conveniado_salarios (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_conveniado_salarios_created_at ON public.conveniado_salarios (created_at);
CREATE INDEX IF NOT EXISTS idx_conveniado_salarios_deleted_at ON public.conveniado_salarios (deleted_at);
CREATE INDEX IF NOT EXISTS idx_conveniados_orgao_expedidor_uf_id ON public.conveniados (orgao_expedidor_uf_id);
CREATE INDEX IF NOT EXISTS idx_conveniados_naturalidade_cidade_id ON public.conveniados (naturalidade_cidade_id);
CREATE INDEX IF NOT EXISTS idx_conveniados_usuario_id ON public.conveniados (usuario_id);
CREATE INDEX IF NOT EXISTS idx_conveniados_cpf ON public.conveniados (cpf);
CREATE INDEX IF NOT EXISTS idx_conveniados_email ON public.conveniados (email);
CREATE INDEX IF NOT EXISTS idx_conveniados_ativo ON public.conveniados (ativo);
CREATE INDEX IF NOT EXISTS idx_conveniados_created_at ON public.conveniados (created_at);
CREATE INDEX IF NOT EXISTS idx_conveniados_deleted_at ON public.conveniados (deleted_at);
CREATE INDEX IF NOT EXISTS idx_conveniados_cargo_id ON public.conveniados (cargo_id);
CREATE INDEX IF NOT EXISTS idx_dados_bancarios_origem_id ON public.dados_bancarios (origem_id);
CREATE INDEX IF NOT EXISTS idx_dados_bancarios_banco_id ON public.dados_bancarios (banco_id);
CREATE INDEX IF NOT EXISTS idx_dados_bancarios_created_at ON public.dados_bancarios (created_at);
CREATE INDEX IF NOT EXISTS idx_dados_bancarios_deleted_at ON public.dados_bancarios (deleted_at);
CREATE INDEX IF NOT EXISTS idx_deflatores_prestadores_contratos_id ON public.deflatores (prestadores_contratos_id);
CREATE INDEX IF NOT EXISTS idx_deflatores_procedimento_grupo_id ON public.deflatores (procedimento_grupo_id);
CREATE INDEX IF NOT EXISTS idx_deflatores_deleted_at ON public.deflatores (deleted_at);
CREATE INDEX IF NOT EXISTS idx_deflatores_created_at ON public.deflatores (created_at);
CREATE INDEX IF NOT EXISTS idx_documentos_origem_id ON public.documentos (origem_id);
CREATE INDEX IF NOT EXISTS idx_documentos_deleted_at ON public.documentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_documentos_created_at ON public.documentos (created_at);
CREATE INDEX IF NOT EXISTS idx_documentos_credenciamento_active ON public.documentos_credenciamento (active);
CREATE INDEX IF NOT EXISTS idx_documentos_credenciamento_deleted_at ON public.documentos_credenciamento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_documentos_credenciamento_created_at ON public.documentos_credenciamento (created_at);
CREATE INDEX IF NOT EXISTS idx_editais_credenciamento_ativo ON public.editais_credenciamento (ativo);
CREATE INDEX IF NOT EXISTS idx_editais_credenciamento_deleted_at ON public.editais_credenciamento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_editais_credenciamento_created_at ON public.editais_credenciamento (created_at);
CREATE INDEX IF NOT EXISTS idx_edital_credenciamento_documentos_edital_id ON public.edital_credenciamento_documentos (edital_id);
CREATE INDEX IF NOT EXISTS idx_edital_credenciamento_documentos_documento_credenciamento_id ON public.edital_credenciamento_documentos (documento_credenciamento_id);
CREATE INDEX IF NOT EXISTS idx_empresa_produto_empresa_id ON public.empresa_produto (empresa_id);
CREATE INDEX IF NOT EXISTS idx_empresa_produto_produto_id ON public.empresa_produto (produto_id);
CREATE INDEX IF NOT EXISTS idx_empresa_user_user_id ON public.empresa_user (user_id);
CREATE INDEX IF NOT EXISTS idx_empresa_user_empresa_id ON public.empresa_user (empresa_id);
CREATE INDEX IF NOT EXISTS idx_empresas_cpf_cnpj ON public.empresas (cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_empresas_email ON public.empresas (email);
CREATE INDEX IF NOT EXISTS idx_empresas_ativo ON public.empresas (ativo);
CREATE INDEX IF NOT EXISTS idx_empresas_created_at ON public.empresas (created_at);
CREATE INDEX IF NOT EXISTS idx_empresas_deleted_at ON public.empresas (deleted_at);
CREATE INDEX IF NOT EXISTS idx_empresas_verbas_empresa_id ON public.empresas_verbas (empresa_id);
CREATE INDEX IF NOT EXISTS idx_empresas_verbas_created_at ON public.empresas_verbas (created_at);
CREATE INDEX IF NOT EXISTS idx_empresas_verbas_deleted_at ON public.empresas_verbas (deleted_at);
CREATE INDEX IF NOT EXISTS idx_empresas_verbas_grupo_verba_id ON public.empresas_verbas (grupo_verba_id);
CREATE INDEX IF NOT EXISTS idx_enderecos_cidade_id ON public.enderecos (cidade_id);
CREATE INDEX IF NOT EXISTS idx_enderecos_origem_id ON public.enderecos (origem_id);
CREATE INDEX IF NOT EXISTS idx_enderecos_ativo ON public.enderecos (ativo);
CREATE INDEX IF NOT EXISTS idx_enderecos_created_at ON public.enderecos (created_at);
CREATE INDEX IF NOT EXISTS idx_enderecos_deleted_at ON public.enderecos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_especialidades_ativo ON public.especialidades (ativo);
CREATE INDEX IF NOT EXISTS idx_especialidades_created_at ON public.especialidades (created_at);
CREATE INDEX IF NOT EXISTS idx_especialidades_deleted_at ON public.especialidades (deleted_at);
CREATE INDEX IF NOT EXISTS idx_estados_ativo ON public.estados (ativo);
CREATE INDEX IF NOT EXISTS idx_estados_created_at ON public.estados (created_at);
CREATE INDEX IF NOT EXISTS idx_estados_deleted_at ON public.estados (deleted_at);
CREATE INDEX IF NOT EXISTS idx_fiscal_contrato_itens_fiscal_contrato_id ON public.fiscal_contrato_itens (fiscal_contrato_id);
CREATE INDEX IF NOT EXISTS idx_fiscal_contrato_itens_contrato_id ON public.fiscal_contrato_itens (contrato_id);
CREATE INDEX IF NOT EXISTS idx_fiscal_contrato_itens_deleted_at ON public.fiscal_contrato_itens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_fiscal_contrato_itens_created_at ON public.fiscal_contrato_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_fiscal_contratos_usuario_id ON public.fiscal_contratos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_fiscal_contratos_ativo ON public.fiscal_contratos (ativo);
CREATE INDEX IF NOT EXISTS idx_fiscal_contratos_deleted_at ON public.fiscal_contratos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_fiscal_contratos_created_at ON public.fiscal_contratos (created_at);
CREATE INDEX IF NOT EXISTS idx_gestantes_conveniado_id ON public.gestantes (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_gestantes_created_at ON public.gestantes (created_at);
CREATE INDEX IF NOT EXISTS idx_gestantes_deleted_at ON public.gestantes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_grau_parentesco_ativo ON public.grau_parentesco (ativo);
CREATE INDEX IF NOT EXISTS idx_grau_parentesco_created_at ON public.grau_parentesco (created_at);
CREATE INDEX IF NOT EXISTS idx_grau_parentesco_deleted_at ON public.grau_parentesco (deleted_at);
CREATE INDEX IF NOT EXISTS idx_grupo_verbas_deleted_at ON public.grupo_verbas (deleted_at);
CREATE INDEX IF NOT EXISTS idx_grupo_verbas_created_at ON public.grupo_verbas (created_at);
CREATE INDEX IF NOT EXISTS idx_guia_importacoes_prestador_id ON public.guia_importacoes (prestador_id);
CREATE INDEX IF NOT EXISTS idx_guia_importacoes_usuario_id ON public.guia_importacoes (usuario_id);
CREATE INDEX IF NOT EXISTS idx_guia_importacoes_deleted_at ON public.guia_importacoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guia_importacoes_created_at ON public.guia_importacoes (created_at);
CREATE INDEX IF NOT EXISTS idx_guia_motivo_encerramento_deleted_at ON public.guia_motivo_encerramento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guia_motivo_encerramento_created_at ON public.guia_motivo_encerramento (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_usuario_emissor_id ON public.guias (usuario_emissor_id);
CREATE INDEX IF NOT EXISTS idx_guias_prestador_id ON public.guias (prestador_id);
CREATE INDEX IF NOT EXISTS idx_guias_profissional_id ON public.guias (profissional_id);
CREATE INDEX IF NOT EXISTS idx_guias_conveniado_id ON public.guias (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_guias_solicitante_prestador_id ON public.guias (solicitante_prestador_id);
CREATE INDEX IF NOT EXISTS idx_guias_lote_pagamento_id ON public.guias (lote_pagamento_id);
CREATE INDEX IF NOT EXISTS idx_guias_guia_origem_id ON public.guias (guia_origem_id);
CREATE INDEX IF NOT EXISTS idx_guias_status ON public.guias (status);
CREATE INDEX IF NOT EXISTS idx_guias_cancelado_por_user_id ON public.guias (cancelado_por_user_id);
CREATE INDEX IF NOT EXISTS idx_guias_guia_importacao_id ON public.guias (guia_importacao_id);
CREATE INDEX IF NOT EXISTS idx_guias_deleted_at ON public.guias (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_created_at ON public.guias (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_anexos_guia_id ON public.guias_anexos (guia_id);
CREATE INDEX IF NOT EXISTS idx_guias_anexos_deleted_at ON public.guias_anexos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_anexos_created_at ON public.guias_anexos (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_atendimentos_guia_itens_id ON public.guias_atendimentos (guia_itens_id);
CREATE INDEX IF NOT EXISTS idx_guias_atendimentos_usuario_id ON public.guias_atendimentos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_guias_atendimentos_created_at ON public.guias_atendimentos (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_atendimentos_deleted_at ON public.guias_atendimentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_auditoria_guia_itens_id ON public.guias_auditoria (guia_itens_id);
CREATE INDEX IF NOT EXISTS idx_guias_auditoria_analise_usuario_id ON public.guias_auditoria (analise_usuario_id);
CREATE INDEX IF NOT EXISTS idx_guias_auditoria_deleted_at ON public.guias_auditoria (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_auditoria_created_at ON public.guias_auditoria (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_historico_guia_id ON public.guias_historico (guia_id);
CREATE INDEX IF NOT EXISTS idx_guias_historico_guia_item_id ON public.guias_historico (guia_item_id);
CREATE INDEX IF NOT EXISTS idx_guias_historico_usuario_id ON public.guias_historico (usuario_id);
CREATE INDEX IF NOT EXISTS idx_guias_historico_deleted_at ON public.guias_historico (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_historico_created_at ON public.guias_historico (created_at);
CREATE INDEX IF NOT EXISTS idx_guias_itens_guia_id ON public.guias_itens (guia_id);
CREATE INDEX IF NOT EXISTS idx_guias_itens_referencia_id ON public.guias_itens (referencia_id);
CREATE INDEX IF NOT EXISTS idx_guias_itens_status ON public.guias_itens (status);
CREATE INDEX IF NOT EXISTS idx_guias_itens_deleted_at ON public.guias_itens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_guias_itens_created_at ON public.guias_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_historico_credenciamentos_solicitacao_credencimento_id ON public.historico_credenciamentos (solicitacao_credencimento_id);
CREATE INDEX IF NOT EXISTS idx_historico_credenciamentos_user_id ON public.historico_credenciamentos (user_id);
CREATE INDEX IF NOT EXISTS idx_historico_credenciamentos_status ON public.historico_credenciamentos (status);
CREATE INDEX IF NOT EXISTS idx_historico_credenciamentos_created_at ON public.historico_credenciamentos (created_at);
CREATE INDEX IF NOT EXISTS idx_laboratorios_created_at ON public.laboratorios (created_at);
CREATE INDEX IF NOT EXISTS idx_laboratorios_deleted_at ON public.laboratorios (deleted_at);
CREATE INDEX IF NOT EXISTS idx_lancamentos_boleto_id ON public.lancamentos (boleto_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_operadora_id ON public.lancamentos (operadora_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_prestador_id ON public.lancamentos (prestador_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_conveniado_id ON public.lancamentos (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_active ON public.lancamentos (active);
CREATE INDEX IF NOT EXISTS idx_lancamentos_deleted_at ON public.lancamentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_lancamentos_created_at ON public.lancamentos (created_at);
CREATE INDEX IF NOT EXISTS idx_lancamentos_grupo_verba_id ON public.lancamentos (grupo_verba_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_guias_lancamento_id ON public.lancamentos_guias (lancamento_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_guias_guia_id ON public.lancamentos_guias (guia_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_guias_deleted_at ON public.lancamentos_guias (deleted_at);
CREATE INDEX IF NOT EXISTS idx_lancamentos_guias_created_at ON public.lancamentos_guias (created_at);
CREATE INDEX IF NOT EXISTS idx_log_acessos_usuario_id ON public.log_acessos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_log_acessos_registro_id ON public.log_acessos (registro_id);
CREATE INDEX IF NOT EXISTS idx_log_acessos_deleted_at ON public.log_acessos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_log_operacoes_usuario_id ON public.log_operacoes (usuario_id);
CREATE INDEX IF NOT EXISTS idx_log_operacoes_registro_id ON public.log_operacoes (registro_id);
CREATE INDEX IF NOT EXISTS idx_log_operacoes_deleted_at ON public.log_operacoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_prestador_id ON public.lote_pagamentos (prestador_id);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_usuario_id ON public.lote_pagamentos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_lancamento_id ON public.lote_pagamentos (lancamento_id);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_status ON public.lote_pagamentos (status);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_deleted_at ON public.lote_pagamentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_lote_pagamentos_created_at ON public.lote_pagamentos (created_at);
CREATE INDEX IF NOT EXISTS idx_materiais_deleted_at ON public.materiais (deleted_at);
CREATE INDEX IF NOT EXISTS idx_materiais_created_at ON public.materiais (created_at);
CREATE INDEX IF NOT EXISTS idx_materiais_itens_material_edicao_id ON public.materiais_itens (material_edicao_id);
CREATE INDEX IF NOT EXISTS idx_materiais_itens_material_id ON public.materiais_itens (material_id);
CREATE INDEX IF NOT EXISTS idx_materiais_itens_deleted_at ON public.materiais_itens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_materiais_itens_created_at ON public.materiais_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_material_edicoes_ativo ON public.material_edicoes (ativo);
CREATE INDEX IF NOT EXISTS idx_material_edicoes_deleted_at ON public.material_edicoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_material_edicoes_created_at ON public.material_edicoes (created_at);
CREATE INDEX IF NOT EXISTS idx_medicamento_brasindice_medicamento_edicao_id ON public.medicamento_brasindice (medicamento_edicao_id);
CREATE INDEX IF NOT EXISTS idx_medicamento_brasindice_medicamento_id ON public.medicamento_brasindice (medicamento_id);
CREATE INDEX IF NOT EXISTS idx_medicamento_brasindice_ativo ON public.medicamento_brasindice (ativo);
CREATE INDEX IF NOT EXISTS idx_medicamento_brasindice_created_at ON public.medicamento_brasindice (created_at);
CREATE INDEX IF NOT EXISTS idx_medicamento_edicoes_ativo ON public.medicamento_edicoes (ativo);
CREATE INDEX IF NOT EXISTS idx_medicamento_edicoes_deleted_at ON public.medicamento_edicoes (deleted_at);
CREATE INDEX IF NOT EXISTS idx_medicamento_edicoes_created_at ON public.medicamento_edicoes (created_at);
CREATE INDEX IF NOT EXISTS idx_medicamentos_laboratorio_id ON public.medicamentos (laboratorio_id);
CREATE INDEX IF NOT EXISTS idx_medicamentos_medicamento_edicao_id ON public.medicamentos (medicamento_edicao_id);
CREATE INDEX IF NOT EXISTS idx_medicamentos_deleted_at ON public.medicamentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_medicamentos_created_at ON public.medicamentos (created_at);
CREATE INDEX IF NOT EXISTS idx_mensagens_perfil_id ON public.mensagens (perfil_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_deleted_at ON public.mensagens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_mensagens_created_at ON public.mensagens (created_at);
CREATE INDEX IF NOT EXISTS idx_mensalidades_conveniado_id ON public.mensalidades (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_mensalidades_produto_preco_id ON public.mensalidades (produto_preco_id);
CREATE INDEX IF NOT EXISTS idx_mensalidades_grupo_verba_id ON public.mensalidades (grupo_verba_id);
CREATE INDEX IF NOT EXISTS idx_mensalidades_deleted_at ON public.mensalidades (deleted_at);
CREATE INDEX IF NOT EXISTS idx_mensalidades_created_at ON public.mensalidades (created_at);
CREATE INDEX IF NOT EXISTS idx_menus_fixed_id ON public.menus (fixed_id);
CREATE INDEX IF NOT EXISTS idx_menus_parent_id ON public.menus (parent_id);
CREATE INDEX IF NOT EXISTS idx_menus_deleted_at ON public.menus (deleted_at);
CREATE INDEX IF NOT EXISTS idx_motivo_encerramentos_ativo ON public.motivo_encerramentos (ativo);
CREATE INDEX IF NOT EXISTS idx_motivo_encerramentos_deleted_at ON public.motivo_encerramentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_motivo_encerramentos_created_at ON public.motivo_encerramentos (created_at);
CREATE INDEX IF NOT EXISTS idx_operadora_user_operadora_id ON public.operadora_user (operadora_id);
CREATE INDEX IF NOT EXISTS idx_operadora_user_user_id ON public.operadora_user (user_id);
CREATE INDEX IF NOT EXISTS idx_operadoras_cpf_cnpj ON public.operadoras (cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_operadoras_email ON public.operadoras (email);
CREATE INDEX IF NOT EXISTS idx_operadoras_ativo ON public.operadoras (ativo);
CREATE INDEX IF NOT EXISTS idx_operadoras_created_at ON public.operadoras (created_at);
CREATE INDEX IF NOT EXISTS idx_operadoras_deleted_at ON public.operadoras (deleted_at);
CREATE INDEX IF NOT EXISTS idx_operadoras_boleto_client_id ON public.operadoras (boleto_client_id);
CREATE INDEX IF NOT EXISTS idx_parametros_deleted_at ON public.parametros (deleted_at);
CREATE INDEX IF NOT EXISTS idx_permission_role_permission_id ON public.permission_role (permission_id);
CREATE INDEX IF NOT EXISTS idx_permission_role_role_id ON public.permission_role (role_id);
CREATE INDEX IF NOT EXISTS idx_permissions_active ON public.permissions (active);
CREATE INDEX IF NOT EXISTS idx_permissions_created_at ON public.permissions (created_at);
CREATE INDEX IF NOT EXISTS idx_personal_access_tokens_created_at ON public.personal_access_tokens (created_at);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_prestadores_contratos_id ON public.prestador_contrato_itens (prestadores_contratos_id);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_edicao_medicamento_id ON public.prestador_contrato_itens (edicao_medicamento_id);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_tabela_precos_id ON public.prestador_contrato_itens (tabela_precos_id);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_ativo ON public.prestador_contrato_itens (ativo);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_deleted_at ON public.prestador_contrato_itens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_created_at ON public.prestador_contrato_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_prestador_contrato_itens_motivo_encerramento_id ON public.prestador_contrato_itens (motivo_encerramento_id);
CREATE INDEX IF NOT EXISTS idx_prestador_contratos_prestador_id ON public.prestador_contratos (prestador_id);
CREATE INDEX IF NOT EXISTS idx_prestador_contratos_ativo ON public.prestador_contratos (ativo);
CREATE INDEX IF NOT EXISTS idx_prestador_contratos_deleted_at ON public.prestador_contratos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_prestador_contratos_created_at ON public.prestador_contratos (created_at);
CREATE INDEX IF NOT EXISTS idx_prestador_especialidades_prestador_id ON public.prestador_especialidades (prestador_id);
CREATE INDEX IF NOT EXISTS idx_prestador_especialidades_especialidade_id ON public.prestador_especialidades (especialidade_id);
CREATE INDEX IF NOT EXISTS idx_prestador_tipos_active ON public.prestador_tipos (active);
CREATE INDEX IF NOT EXISTS idx_prestador_tipos_deleted_at ON public.prestador_tipos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_prestador_tipos_created_at ON public.prestador_tipos (created_at);
CREATE INDEX IF NOT EXISTS idx_prestador_user_prestador_id ON public.prestador_user (prestador_id);
CREATE INDEX IF NOT EXISTS idx_prestador_user_user_id ON public.prestador_user (user_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_usuario_id ON public.prestadores (usuario_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_prestadores_classificacao_estabelecimento_id ON public.prestadores (prestadores_classificacao_estabelecimento_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_orgao_expedidor_uf_id ON public.prestadores (orgao_expedidor_uf_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_naturalidade_cidade_id ON public.prestadores (naturalidade_cidade_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_cpf_cnpj ON public.prestadores (cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_prestadores_email ON public.prestadores (email);
CREATE INDEX IF NOT EXISTS idx_prestadores_ativo ON public.prestadores (ativo);
CREATE INDEX IF NOT EXISTS idx_prestadores_created_at ON public.prestadores (created_at);
CREATE INDEX IF NOT EXISTS idx_prestadores_deleted_at ON public.prestadores (deleted_at);
CREATE INDEX IF NOT EXISTS idx_prestadores_prestador_tipo_id ON public.prestadores (prestador_tipo_id);
CREATE INDEX IF NOT EXISTS idx_prestadores_classificacao_estabelecimento_ativo ON public.prestadores_classificacao_estabelecimento (ativo);
CREATE INDEX IF NOT EXISTS idx_prestadores_classificacao_estabelecimento_created_at ON public.prestadores_classificacao_estabelecimento (created_at);
CREATE INDEX IF NOT EXISTS idx_prestadores_classificacao_estabelecimento_deleted_at ON public.prestadores_classificacao_estabelecimento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_procedimento_subgrupos_grupo_id ON public.procedimento_subgrupos (grupo_id);
CREATE INDEX IF NOT EXISTS idx_procedimento_subgrupos_created_at ON public.procedimento_subgrupos (created_at);
CREATE INDEX IF NOT EXISTS idx_procedimento_subgrupos_deleted_at ON public.procedimento_subgrupos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_procedimentos_procedimento_subgrupo_id ON public.procedimentos (procedimento_subgrupo_id);
CREATE INDEX IF NOT EXISTS idx_procedimentos_created_at ON public.procedimentos (created_at);
CREATE INDEX IF NOT EXISTS idx_procedimentos_deleted_at ON public.procedimentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_procedimentos_grupos_ativo ON public.procedimentos_grupos (ativo);
CREATE INDEX IF NOT EXISTS idx_procedimentos_grupos_created_at ON public.procedimentos_grupos (created_at);
CREATE INDEX IF NOT EXISTS idx_procedimentos_grupos_deleted_at ON public.procedimentos_grupos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_produtos_operadora_id ON public.produtos (operadora_id);
CREATE INDEX IF NOT EXISTS idx_produtos_ativo ON public.produtos (ativo);
CREATE INDEX IF NOT EXISTS idx_produtos_created_at ON public.produtos (created_at);
CREATE INDEX IF NOT EXISTS idx_produtos_deleted_at ON public.produtos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_produtos_precos_produto_id ON public.produtos_precos (produto_id);
CREATE INDEX IF NOT EXISTS idx_produtos_precos_tipo_vinculo_id ON public.produtos_precos (tipo_vinculo_id);
CREATE INDEX IF NOT EXISTS idx_produtos_precos_created_at ON public.produtos_precos (created_at);
CREATE INDEX IF NOT EXISTS idx_produtos_precos_deleted_at ON public.produtos_precos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_produtos_precos_grupo_verba_id ON public.produtos_precos (grupo_verba_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_produto_id ON public.regra_cooparticipacao (produto_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_ativo ON public.regra_cooparticipacao (ativo);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_created_at ON public.regra_cooparticipacao (created_at);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_deleted_at ON public.regra_cooparticipacao (deleted_at);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_itens_regra_cooparticipacao_id ON public.regra_cooparticipacao_itens (regra_cooparticipacao_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_itens_created_at ON public.regra_cooparticipacao_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_itens_deleted_at ON public.regra_cooparticipacao_itens (deleted_at);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_regra_cooparticipacao_id ON public.regra_cooparticipacao_procedimentos (regra_cooparticipacao_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_grupo_procedimento_id ON public.regra_cooparticipacao_procedimentos (grupo_procedimento_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_subgrupo_procedimento_id ON public.regra_cooparticipacao_procedimentos (subgrupo_procedimento_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_procedimento_id ON public.regra_cooparticipacao_procedimentos (procedimento_id);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_created_at ON public.regra_cooparticipacao_procedimentos (created_at);
CREATE INDEX IF NOT EXISTS idx_regra_cooparticipacao_procedimentos_deleted_at ON public.regra_cooparticipacao_procedimentos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_empresa_id ON public.remessa_desconto (empresa_id);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_deleted_at ON public.remessa_desconto (deleted_at);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_created_at ON public.remessa_desconto (created_at);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_item_remessa_desconto_id ON public.remessa_desconto_item (remessa_desconto_id);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_item_adesao_id ON public.remessa_desconto_item (adesao_id);
CREATE INDEX IF NOT EXISTS idx_remessa_desconto_item_created_at ON public.remessa_desconto_item (created_at);
CREATE INDEX IF NOT EXISTS idx_role_user_user_id ON public.role_user (user_id);
CREATE INDEX IF NOT EXISTS idx_role_user_role_id ON public.role_user (role_id);
CREATE INDEX IF NOT EXISTS idx_roles_active ON public.roles (active);
CREATE INDEX IF NOT EXISTS idx_roles_created_at ON public.roles (created_at);
CREATE INDEX IF NOT EXISTS idx_secretarias_empresa_id ON public.secretarias (empresa_id);
CREATE INDEX IF NOT EXISTS idx_secretarias_cpf_cnpj ON public.secretarias (cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_secretarias_email ON public.secretarias (email);
CREATE INDEX IF NOT EXISTS idx_secretarias_ativo ON public.secretarias (ativo);
CREATE INDEX IF NOT EXISTS idx_secretarias_created_at ON public.secretarias (created_at);
CREATE INDEX IF NOT EXISTS idx_secretarias_deleted_at ON public.secretarias (deleted_at);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_prestador_id ON public.solicitacoes_atualizacao_cadastral (prestador_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_conveniado_id ON public.solicitacoes_atualizacao_cadastral (conveniado_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_cidade_id ON public.solicitacoes_atualizacao_cadastral (cidade_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_email ON public.solicitacoes_atualizacao_cadastral (email);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_status ON public.solicitacoes_atualizacao_cadastral (status);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_deleted_at ON public.solicitacoes_atualizacao_cadastral (deleted_at);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_atualizacao_cadastral_created_at ON public.solicitacoes_atualizacao_cadastral (created_at);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_edital_credenciamento_id ON public.solicitacoes_credenciamento (edital_credenciamento_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_cpf_cnpj ON public.solicitacoes_credenciamento (cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_email ON public.solicitacoes_credenciamento (email);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_deleted_at ON public.solicitacoes_credenciamento (deleted_at);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_created_at ON public.solicitacoes_credenciamento (created_at);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_documentos_solicitacoes_credenciamento_id ON public.solicitacoes_credenciamento_documentos (solicitacoes_credenciamento_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_documentos_documento_credenciamento_id ON public.solicitacoes_credenciamento_documentos (documento_credenciamento_id);
CREATE INDEX IF NOT EXISTS idx_solicitacoes_credenciamento_documentos_created_at ON public.solicitacoes_credenciamento_documentos (created_at);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_comunicado_edicao_id ON public.tabela_precos (comunicado_edicao_id);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_cbhpm_edicao_id ON public.tabela_precos (cbhpm_edicao_id);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_material_edicao_id ON public.tabela_precos (material_edicao_id);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_ativo ON public.tabela_precos (ativo);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_deleted_at ON public.tabela_precos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_created_at ON public.tabela_precos (created_at);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_itens_tabela_preco_id ON public.tabela_precos_itens (tabela_preco_id);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_itens_referencia_id ON public.tabela_precos_itens (referencia_id);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_itens_created_at ON public.tabela_precos_itens (created_at);
CREATE INDEX IF NOT EXISTS idx_taxas_deleted_at ON public.taxas (deleted_at);
CREATE INDEX IF NOT EXISTS idx_taxas_created_at ON public.taxas (created_at);
CREATE INDEX IF NOT EXISTS idx_tipo_vinculos_ativo ON public.tipo_vinculos (ativo);
CREATE INDEX IF NOT EXISTS idx_tipo_vinculos_deleted_at ON public.tipo_vinculos (deleted_at);
CREATE INDEX IF NOT EXISTS idx_tipo_vinculos_created_at ON public.tipo_vinculos (created_at);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_cpf ON public.users (cpf);
CREATE INDEX IF NOT EXISTS idx_users_active ON public.users (active);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users (created_at);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON public.users (deleted_at);

-- ============================================================
-- Observações importantes
-- ============================================================
-- 1. Este script corrige estrutura básica, chaves primárias e compatibilidade.
-- 2. As FOREIGN KEYS não foram adicionadas automaticamente para evitar erros por tabelas ausentes ou relações ambíguas.
-- 3. Recomenda-se validar as relações antes de aplicar constraints definitivas.
-- 4. Para Supabase, habilite RLS manualmente por módulo após definir perfis e permissões.
